@Library('jenkins-devops@dev')_ // load jenkins-devops as a library

pipeline {
  agent {
    label 'werf'
  }
  environment {
      SECRET_FILE_ID = credentials("ya_registry_key")
      A              = '1'
  }
  stages { //* Pass
    stage('Password') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'id-key', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {

              password = env.PASSWORD

              sh "echo pass $PASSWORD" 
          }
          echo "PASS ${password}"
        }
      }
    }
  }
  post { //* Post Action
    always {
      script {
        if (SendNotification == 'true') {
          functions.postActionBuildResult("${SlackChannel}")
        }
      }
    }
    success {
      script { //* Auto Deploy
        if (env.BRANCH_NAME == 'dev') {
          echo "=====> Start deploy to dev-namespace"
          build job: 'Team.XXX(K8S)/XXX.XXX/dev', wait: true
          echo "frontend url: https://XXX.ru/ "
          echo "cms url: https://XXX.ru/ "
        } 
        else if (env.BRANCH_NAME == 'prod') {
          echo "=====> Start deploy to production"
          build job: 'Team.APEX(K8S)/apex.entrypoint/master', wait: true
        }
      }
    }
  } //* EOF Post Action
}
----------------
  
          stage('helm-publish in for') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'npm-uploader', passwordVariable: 'PASS', usernameVariable: 'UN')]) {
                    script {
                        String[] tags;
                        tags = helmTags.split(' ');
                        for (String value : tags){
                            helm_chart_path = ".helm/Chart.yaml"
                            text = readFile(helm_chart_path).trim().replaceAll("VERSION_REPLACE", value)
                            writeFile(file: helm_chart_path, text: text)
                            sh """
                                echo publishing...
                                helm package .helm
                                lst=\$(ls *.tgz 2> /dev/null)
                                cnt=\$(echo \$lst | wc -w)
                                [ \$cnt -eq 0 ] && echo 'No helm-packages for publish' && exit 0
                                echo 'Publishing packages:'
                                find -type f -name *.tgz -print0 | xargs -r0i -n1 curl -u ${UN}:${PASS} https://nexus.ap-team.ru/repository/helm-hosted/ --upload-file {} && echo 'All helm-packages published to' https://nexus.ap-team.ru/repository/helm-hosted/ && exit 0 || exit 252
                                find -type f -name *.tgz -exec rm -rf {} \\;
                                exit 251
                            """
                            text = readFile(helm_chart_path).trim().replaceAll(value, "VERSION_REPLACE")
                            writeFile(file: helm_chart_path, text: text)
                        }
                    }
                }
            }
        }
        
        stage('helm-publish') {
            steps {
                script {
                  helm_chart_path = ".helm/Chart.yaml"
                  text = readFile(helm_chart_path).trim().replaceAll("VERSION_REPLACE", "${helmTag}")
                  writeFile(file: helm_chart_path, text: text)
                }
                withCredentials([usernamePassword(credentialsId: 'npm-uploader', passwordVariable: 'PASS', usernameVariable: 'UN')]) {
                    script {
                        sh """
                            echo publishing...
                            helm package .helm
                            lst=\$(ls *.tgz 2> /dev/null)
                            cnt=\$(echo \$lst | wc -w)
                            [ \$cnt -eq 0 ] && echo 'No helm-packages for publish' && exit 0
                            echo 'Publishing packages:'
                            find -type f -name *.tgz -print0 | xargs -r0i -n1 curl -u ${UN}:${PASS} https://nexus.ap-team.ru/repository/helm-hosted/ --upload-file {} && echo 'All helm-packages published to' https://nexus.ap-team.ru/repository/helm-hosted/ && exit 0 || exit 252
                            exit 251
                        """
                    }
                }
            }
        }

--------------------------------
